name: CI/CD Vue Frontend

on:
  push:
    branches: [ "frontend" ]
<<<<<<< HEAD
  workflow_dispatch:
=======
>>>>>>> 33a42f8e1063e1f4c3d46c7b15244967fcf42b62

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar frontend
      run: |
        cd PF_Frontend
        npm install

    - name: Build Vue
      run: |
        cd PF_Frontend
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./PF_Frontend/dist
